### ISSUE TITLE
If song title contains question mark, it throws

### ISSUE THREAD

**Issue by avoss** [realtimerealbook/ireal-parse#5]
To fix this, I had to change util/parse.js:
```
-        const fn = parsed.songs[i].title.replace(/\s/g, '_');
+        const fn = parsed.songs[i].title.replace(/[\?\s]/g, '_');
```

**Comment by avoss** [comment]
Hi Poh, thanks for fixing the other issue so quickly. I'm working on a somewhat related project - see www.jamtrackgenerator.com. Maybe we can collaborate somehow?

**Comment by pohzipohzi** [comment]
Hi @avoss. Thanks for submitting this issue. I don't think question marks are a problem as they are automatically encoded as `%3F` (eg "Have You Met Miss Jones?")

Do you have any ideas on how you want to collaborate? My main project is a collaborative chart editor, something like combining iReal Pro and Google Sheets together (see [rtrb.io](rtrb.io)). One project that I have long dreamt of is to add some kind of midi comping engine, but I wouldn't say that it is a really essential feature to have. Also, I intend to keep my project open source unless too many people start using it and server costs become too high.

**Comment by avoss** [comment]
Questionmark does not work in windows ;-)

Regarding collaboration, I thought it may be a good idea if rtrb users could generate a playback track from their chord progression. But my project is not yet ready for this, so maybe let us discuss later when both projects are more mature. BTW, at the bottom of the page I mentioned you find my PM address if you like to talk more privately.
